apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hide-namespace-webhook-deployment
  namespace: hide-namespace
  labels:
    app: hide-namespace
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hide-namespace
    spec:
      containers:
        - name: hide-namespace
          image: praveendhac/hidenamespace:flask-hn-certv1 
          imagePullPolicy: Always 
          ports:
          - containerPort: 443

