apiVersion: v1
kind: Service
metadata:
  name: hide-namespace-webhook-svc
  namespace: hide-namespace
  labels:
    app: hide-namespace
spec:
  ports:
  - port: 443
    targetPort: 5000
  selector:
    app: hide-namespace
